### ISSUE TITLE
Implement "Style Upload" functionality for Layers on GeoNode when GeoServer is enabled

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#21]

**Comment by meyerch** [comment]
How does this work? 
I tried uploading a layer (http://ihp-wins-dev.geo-solutions.it/layers/geonode:river_basins_subunits3), and then uploading the SLD style through "Edit layer" ---> "Upload style", but ended up with the following message:

![upload_sld.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fd84962c8387969ce5bb01e81fe086264c22703d46f96925dce22ceb172f07090e4bae440e5f44fff98d2ba7b33a72984019af80330b2b9b645bf9fa9015ad03ba2a8a4a85b1bc8e4ac0e8352dee8e9d02.PNG)

**Comment by meyerch** [comment]
Now I can upload an SLD directly from 'Edit layer'-->'Upload style'. 
However, I did a few tests, and the style that appears differs from the style I saved in QGIS, in terms of colours, thickness of the borders.
Screenshot below shows the result of SLD upload with this layer (http://ihp-wins-dev.geo-solutions.it/layers/geonode:wpdxhaiti_2017_03_15t4_46). Style is supposed to be the same as for the layer underneath in the list
![sld_differences.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fb989e1c868aaf89ecad46aa5ef5876b0a65633b0ba92e7391a172fd1722000b5b4ba8170e0e41fefcdf2ba6b53c748a5d0eebd37f4366846c4ff8e7df46f554f832815d84b1b68b49c0ef3f2de78e8c4e3919060ac4.PNG)

**Comment by meyerch** [comment]
for this layer http://ihp-wins-dev.geo-solutions.it/layers/geonode:wpdxhonduras_2017_03_15t11_14_12_last1, I also uploaded the SLD. You can see that both points have the same symbol/colour. 
They should like in this layer: http://ihp-wins-dev.geo-solutions.it/layers/geonode:wpdxguatemala_2017_03_15t4_44_53_last

**Comment by meyerch** [comment]
With this layer (http://ihp-wins-dev.geo-solutions.it/layers/geonode:lac_nonindigenous_access_to_piped_water2l), I ended up with nothing when uploading the SLD directly on WINS. Nothing on the map, nothing in the legend. [I used gabin.archambault account to upload it]
See creenshot below
![empty_layer_gabin.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46ed998a379bbca58ef0ba519b5af1962048653f6b14b1247a80e03cfd183954560e1aa8445c0912adfc8b2ef0b63c738a580becd46b5d66da2f53fde6d640e258f075c95d8fa4bd8d46c1ed3d22e582874a3a18001888ed10.PNG)

**Comment by afabiani** [comment]
The SLD Upload should now work and also the compatibility with QGIS client should be improved. About this, I kindly suggest to start using QGIS 3 which has some PRs from Andrea Aime improving SLD compatibility also.

I noticed something about this tough. Basically the SLD upload works and the SLD is correctly stored on GeoServer. I'm facing an issue currently when I upload the SLD from GeoNode. Until I click "Apply" on GeoServer, the QGIS rules are not correctly applied. This is something related to GeoServer, a minor issue which must be identified and fixed.

**Comment by meyerch** [comment]
Please let me know when this is fixed, so I can test is and approve it.

**Comment by afabiani** [comment]
Done

**Comment by meyerch** [comment]
I did one test for now and noticed a strange behavior (on a side note, I clean the cache regularly as you recommended so I don't think it is related to this)
I uploaded this layer http://ihp-wins-dev.geo-solutions.it/layers/geonode:typhfevfem with najet.guefradj account (regular user). 
I uploaded through the normal procedure: upload of the SHP/SHX/DBF/PRJ, then upload of the SLD through 'Upload SLD', then 'Layer info'.


As najet.guefradj, I end up with this:
![sld-upload.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fb989e6e9793a580e8bb01e81fe086264c22703d46f96925dce22ceb172f07090e4bae440e5f44fff98d2ba7b33a72984019af80330b2b9b645bf9fa9015ad00b22a8a4a85bebb8e4ac5e93924e08e9d02.PNG)

Then I logged out, and logged in with Chloe.Meyer (admin), and... the exact same layer shows up correctly (except for the width of the border, which is larger than what I set un GQIS [1 instead of 0.2]):
![sld-upload2.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fb989e6e9793a580e8bb11e611b2843b492d762a10e17132d0ba29bb162e5509091fa9435d0944fcfa892fa6b73976884e17ff933c0120996048e6edc00db513bb27814e80b6b48d48c6e03c25e48f885d73.PNG)

**Comment by afabiani** [comment]
Hi Chloe,
I did several tests following the same path. Usually the issue is always related to the browser cache, infact the style is shown later. Nevertheless I will test it again using your exact layer and style (no need to send me the files, I can recover them from GeoNode. However if you can also send them to me via email it would be helpful).

About the second issue, please notice that the SLD compatibility improvements on QGIS done by Andrea have been merged since QGIS 3.0. The borders thickness still remains with QGIS 2* versions. It can be mitigated if you choose pixel instead of millimiters as unit of measure of the style before exporting it as SLD.

**Comment by meyerch** [comment]
Ok, thanks for the quick reply.
I will recheck with another layer.

As for QGIS 3, is it already available for download?  I can't find it on the website.

**Comment by meyerch** [comment]
I did a second test using Najet.guefradj account once again (here's the layer: http://ihp-wins-dev.geo-solutions.it/layers/geonode:floodoccurence_1), and it worked!
Still have the same issue with border width (I'll try with pixels as measuring unit instead) and grey zones though.

I will run some other tests before accepting this task. Thanks!

**Comment by afabiani** [comment]
Dear Chloe,
I just noticed that the previous had some issues due to a temporary malfunction of GeoServer.

I'll monitor it and do more tests along the day in order to understand if there still some unstability.

**Comment by meyerch** [comment]
Ok, perfect

**Comment by afabiani** [comment]
Dear Chloe,
I have found a misconifguration on GeoFence plugin now fixed. GeoServer seems stable again now. Will continue testing myself too.

**Comment by meyerch** [comment]
Thanks for your feedback

**Comment by meyerch** [comment]
Hi, 
Following the previous messages, I came accross the same issue yesterday and today. 
Using najet.guefradj account, I uploaded somes layers/SLD/edited metadata.

I encountered no problem with the following ones: 
     - http://ihp-wins-dev.geo-solutions.it/layers/geonode:wash_deaths_number1 
     - http://ihp-wins-dev.geo-solutions.it/layers/geonode:data_diarrhoea 
     - http://ihp-wins-dev.geo-solutions.it/layers/geonode:actualevap 
     - http://ihp-wins-dev.geo-solutions.it/layers/geonode:paratf_fem
That is to say: the style was correctly displayed in the viewer after cleaning the cache, and as an Admin, I was able to "approve" and "publish" the layers, which can now be seen by Anonymous users. 

However, I came accross issues for many other layers: 
    - http://ihp-wins-dev.geo-solutions.it/layers/geonode:paratf_male
    - http://ihp-wins-dev.geo-solutions.it/layers/geonode:popwwcoll
    - http://ihp-wins-dev.geo-solutions.it/layers/geonode:typhfevfem_1
    - http://ihp-wins-dev.geo-solutions.it/layers/geonode:typhfevmale
    - http://ihp-wins-dev.geo-solutions.it/layers/geonode:nationalrainfallindex2
    - http://ihp-wins-dev.geo-solutions.it/layers/geonode:floodoccurence_1
    - http://ihp-wins-dev.geo-solutions.it/layers/geonode:freshgwabs2
    - http://ihp-wins-dev.geo-solutions.it/layers/geonode:freshswabs2
    - http://ihp-wins-dev.geo-solutions.it/layers/geonode:precipitation1_1
    - http://ihp-wins-dev.geo-solutions.it/layers/geonode:internalflow3

**Comment by afabiani** [comment]
Hi, yes, it is a permission issue on GeoServer. Due to the problem on Friday most layers security rules may have been messed up.

In this case we need to check the layers having issues and regenerate the permissions. Let me have a quick look at them.

**Comment by afabiani** [comment]
Dear Chloe,
I confirm that the security rules on GeoServer for those layers were not created. I'm regenerating them by simply go to the layer page and clicking on "Change Permissions" > "Apply Permissions".

Notice that on GeoNode core there are plans to create a management command to check and restore missing permissions that can also be run periodically. This is something still open on GeoNode community however.

I'm going one by one, if you find some other layer not working correctly, please try to do the same procedure or just let me know.

**Comment by meyerch** [comment]
Ok  , Thanks for the quick response.

**Comment by meyerch** [comment]
I have one more question, regarding the fact that on some layers, the grey areas are not displayer in the map (although being always displayed in the legend):  What can I do to make sure that the grey areas are correctly dipslayed in the viewer? 

Usually we use grey for  "no data" zones. On some layers, it is well displayed [], but on others, the colour just does not show up []. 
And  when I use the "style editing" tool in the viewer and chose a different colour for those grey areas, they still remain invisible.

**Comment by afabiani** [comment]
It depends on the rule applied basically.
This also should be something fixed by @aaime  in the QGIS exporter. As far as I remember the NO DATA rule on the exported SLD was not correct.

Can you point me to a Layer not showing the grey area?

**Comment by meyerch** [comment]
Sorry I forgot the links: 
http://ihp-wins-dev.geo-solutions.it/layers/geonode:freshgwabs2

**Comment by afabiani** [comment]
Just checked and I confirm that the issue is on the rule translation. Maybe QGis is able to interpret this anyway, but the rule is wrong for sure on SLD.

Currently if you download the SLD you can see the boundaries of the NO DATA rule as follows:

```          <sld:Name>No data for 2007</sld:Name>
          <sld:Title>No data for 2007</sld:Title>
          <ogc:Filter>
            <ogc:And>
              <ogc:PropertyIsGreaterThan>
                <ogc:PropertyName>y2007</ogc:PropertyName>
                <ogc:Literal>-99</ogc:Literal>
              </ogc:PropertyIsGreaterThan>
              <ogc:PropertyIsLessThanOrEqualTo>
                <ogc:PropertyName>y2007</ogc:PropertyName>
                <ogc:Literal>0</ogc:Literal>
              </ogc:PropertyIsLessThanOrEqualTo>
            </ogc:And>
          </ogc:Filter>
```

If you notice the first condition is wrong, it should be ```ogc:PropertyIsGreaterOrEqualThan``` instead of ```ogc:PropertyIsGreaterThan```

It is possible to fix this easily from the integrated style editor also (see the screenshot)
![2017-10-24 18_00_06-Fresh groundwater abstracted in 2007 — ihp-wins-dev.geo-solutions.it.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/560e3e2385de497500b360f6/125516c66e82c728ace21e0d46bac4cb74cfd2f9c2bbeb03f505cfc4797977256422b12e638da32fad4d6e0f0b181fe8141a4f15aebacd69f7e57825de4c52b3c16f5f74c12dc31c1c9246e741a767d211c6abe8df0adebf687afac8d0137b5a5c47d7bc436ce48b57da18b414bb1806e0013c71e37f672843911a237a3a6224aeaadf56848564a4bb152954dafff6b8474cf523859e4324214751b82b35bf035f89689040795debbcc5f4115e45.png)

**Comment by meyerch** [comment]
Thank you for the detailed response!

**Comment by meyerch** [comment]
Hi, 
Is the process to upload sld for raster data the same as for vector data? 
This is the first time I did the the test with a raster (sld was generaetd with the "sld4raster" plugin in qgis), and I ended up with the following message when uploading the sld:

![sld-raster.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c90ce9c2355f0011ed2e90/125516c66e82c728ace21e0d46fb989e6e9082ba9becad01e81fe086264c22703d46f96925dce22ceb172f07090e4bae440e5f44fff98d2ba7b33a72984019af80330b2b9b645bf9fa9015ad00b22a8a4a85bfbe8c4bc8eb3f25e58b9d02.PNG)

**Comment by afabiani** [comment]
On it.

**Comment by afabiani** [comment]
Fixed.

![2017-10-30 13_15_31-geonode-gwpollriskafriotest — ihp-wins-dev.geo-solutions.it.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/560e3e2385de497500b360f6/125516c66e82c728ace21e0d46bac4cb74cfd2f9c2baef03f50ecfc57c7974226403a6247e8ae72df2456c11000312ee181b0415aabbd074e2e37f349a8ebb49c1340734db7a48f2fb9f4bea47a477de1098f5e3d60984b1627ba495d60b2c021758cba00760f3dd59c24af342b01951a1176035b773347911941e762c6f6727aefadd449b9722f5e444700b91a9b1b80418b37dd0cd0874635c58ac2f3ab6035c8a638a0b.png)

**Comment by meyerch** [comment]
accepted
